FROM php:7.4-fpm

# Установка необходимых расширений PHP
# RUN docker-php-ext-install mysqli pdo pdo_mysql

# Копирование исходного кода приложения
COPY app /var/www/html

# Установка прав
RUN chown -R www-data:www-data /var/www/html

# Рабочая директория
WORKDIR /var/www/html